### ISSUE TITLE
Readme question

### ISSUE THREAD

**Issue by jaydgoss** [egaebel/sony-headphones-hack#3]
>  it seems like Sony realized that people didn't like the voice and so they actually started allowing users to disable it

Any idea how to do that?  I tried toggling off "Notification & Voice Guide" in the headphones app, doesn't seem to make a difference.  As far as I can tell I have the latest software.

**Comment by beIina** [comment]
you've probably figured out already, but there is just no way to disable the voice prompts that are considered fundamental by sony (i.e. power on/off, bluetooth device connected). there are many back and forths about this all over the internet, and so far it still got nowhere. i am at my wits' end just hoping that someday they will release an update that replaces the atrocious voice with something more subtle like beeps.
